#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.ssb_admin_id = "@5Pt3dKy2HTJ0mWuS78oIiklIX0gBz6BTfEnXsbvke9c=.ed25519"
    args.password = "1Strong-Password"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.c759c5f400660031676a0f92d5c5ffcc68bd6da9.name = "2.0.6~ynh3"
