#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# CREATE FIRST ADMIN USER
#=================================================
ynh_script_progression "Creating first ssbroom admin user"

ynh_exec_as_app /usr/bin/expect<<EOF
set force_conservative 0  ;
set timeout -1
spawn sh -c "$install_dir/insert-user -repo $data_dir $ssb_admin_id"
match_max 100000
expect "*?assword: "
send -- "$password\r"
expect "*?assword: "
send -- "$password\r"
expect eof
EOF

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add $app --description="Secure Scuttlebutt room server" --log="/var/log/$app/$app.log" --needs_exposed_ports $port_ssb

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"  --wait_until="event=serving"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
